Repository JurisFund/JurisFund-monorepo, pull requests merged in 2023-12, with the labels that each got.

#9 feat: created applications list page for admins review
  apps/jurisfund/src/pages/applications/[applicationID].tsx
  apps/jurisfund/src/pages/applications/index.tsx
  apps/jurisfund/src/server/api/routers/applications.ts
  packages/next-config/nextpwa.config.js
Labels: enhancement

#10 feat: applications approval first round
  apps/jurisfund/src/components/Header.tsx
  apps/jurisfund/src/pages/applications/[...applicationID].tsx
  apps/jurisfund/src/pages/applications/[applicationID].tsx
  apps/jurisfund/src/pages/applications/index.tsx
  apps/jurisfund/src/server/api/routers/applications.ts
  packages/database/prisma/schema.prisma
Labels: enhancement

#11 Feat: new case option in borrower case application form
  apps/jurisfund/src/pages/borrower/application/index.tsx
Labels: enhancement

#13 feat: responsive and project enahcenments
  apps/jurisfund/public/jf-letters-original.png
  apps/jurisfund/src/components/Footer.tsx
  apps/jurisfund/src/components/Header.tsx
  apps/lending/example .env.local
  apps/lending/public/jf-letters-original.png
  packages/ui/src/components/Footer/Footer.tsx
  packages/ui/src/components/Navigation/Navigation.tsx
Labels: enhancement

#15 feat: update navigation links on header
  apps/jurisfund/src/components/Header.tsx
Labels: enhancement

#16 feat: updated description texts as doc
  apps/jurisfund/src/next-seo.config.ts
  apps/jurisfund/src/pages/_document.tsx
  apps/jurisfund/src/pages/index.tsx
Labels: enhancement

#14 feat: nav links + seo + new description
  apps/jurisfund/src/components/Header.tsx
  apps/jurisfund/src/next-seo.config.ts
  apps/jurisfund/src/pages/_document.tsx
  apps/jurisfund/src/pages/index.tsx
  apps/lending/src/pages/index.tsx
Labels: bug

#20 feat: some responsivess enhancements and new a new providers component
  apps/jurisfund/package.json
  apps/jurisfund/src/components/Layout.tsx
  apps/jurisfund/src/components/Providers.tsx
  apps/jurisfund/src/pages/_app.tsx
  apps/jurisfund/src/pages/borrower/application/index.tsx
  apps/jurisfund/src/pages/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#22 feat: new get started/onboarding page
  apps/jurisfund/src/components/Header.tsx
  apps/jurisfund/src/components/Layout.tsx
  apps/jurisfund/src/pages/borrower/[...userId].tsx
  apps/jurisfund/src/pages/borrower/application/success.tsx
  apps/jurisfund/src/pages/borrower/apply/index.tsx
  apps/jurisfund/src/pages/borrower/apply/success.tsx
  apps/jurisfund/src/pages/borrower/index.tsx
  apps/jurisfund/src/pages/index.tsx
  packages/ui/src/components/Navigation/Navigation.tsx
Labels: enhancement

#26 feat: changed nav option url
  apps/jurisfund/src/components/Header.tsx
Labels: enhancement

#27 feat: mobile menu popover
  packages/ui/src/components/Navigation/MobileNavigation.tsx
  packages/ui/src/components/Navigation/Navigation.tsx
Labels: enhancement

#29 feat: created admin app project
  apps/admins/.storybook/main.js
  apps/admins/.storybook/manager.js
  apps/admins/.storybook/preview.js
  apps/admins/example .env.local
  apps/admins/jest.config.js
  apps/admins/next-env.d.ts
  apps/admins/next.config.js
  apps/admins/package.json
  apps/admins/postcss.config.js
  apps/admins/public/android-chrome-192x192.png
  apps/admins/public/apple-touch-icon.png
  apps/admins/public/browserconfig.xml
  apps/admins/public/favicon-16x16.png
  apps/admins/public/favicon-32x32.png
  apps/admins/public/favicon.ico
  apps/admins/public/jf-letters-original.png
  apps/admins/public/mstile-150x150.png
  apps/admins/public/safari-pinned-tab.svg
  apps/admins/public/site.webmanifest
  apps/admins/src/components/Footer.tsx
  apps/admins/src/components/Header.tsx
  apps/admins/src/components/Layout.tsx
  apps/admins/src/components/Providers.tsx
  apps/admins/src/env.mjs
  apps/admins/src/next-seo.config.ts
  apps/admins/src/pages/404.tsx
  apps/admins/src/pages/_app.tsx
  apps/admins/src/pages/_document.tsx
  apps/admins/src/pages/api/trpc/[trpc].ts
  apps/admins/src/pages/applications/[...applicationID].tsx
  apps/admins/src/pages/applications/index.tsx
  apps/admins/src/pages/index.tsx
  apps/admins/src/pages/login.tsx
  apps/admins/src/server/api/root.ts
  apps/admins/src/server/api/routers/applications.ts
  apps/admins/src/server/api/routers/example.ts
  apps/admins/src/server/api/trpc.ts
  apps/admins/src/server/auth.ts
  apps/admins/src/server/transformer.ts
  apps/admins/src/styles.css
  apps/admins/src/utils/api.ts
  apps/admins/tailwind.config.js
  apps/admins/tsconfig.json
  apps/website/next.config.js
  apps/website/package.json
  apps/website/src/components/Header.tsx
  apps/website/src/components/Layout.tsx
  apps/website/src/pages/Home.stories.tsx
  apps/website/src/pages/Home.test.tsx
  apps/website/src/pages/_app.page.tsx
  apps/website/src/pages/_document.page.tsx
  apps/website/src/pages/index.page.tsx
  package.json
  pnpm-lock.yaml
  turbo.code-workspace
  turbo.json
Labels: enhancement

#31 feat: small css change
  apps/admins/src/pages/index.tsx
Labels: enhancement

#38 feat: cleanup
  apps/admins/package.json
  apps/admins/src/components/Providers.tsx
  apps/admins/src/server/auth.ts
  apps/jurisfund/package.json
  apps/lending/package.json
  pnpm-lock.yaml
Labels: enhancement, admin app, borrowers app, lending app

#39 feat: changed to rainbowkit wallet connection on admins app
  apps/admins/package.json
  apps/admins/src/components/Header.tsx
  apps/admins/src/components/Providers.tsx
  apps/admins/src/pages/_app.tsx
  apps/admins/src/pages/index.tsx
  apps/admins/src/pages/login.tsx
  pnpm-lock.yaml
Labels: enhancement, admin app

#41 feat: testing purposes deploy
  apps/admins/public/.well-known/walletconnect.txt
  apps/admins/public/walletconnect.txt
Labels: admin app

#42 feat: some stilying and wallet connect buttons update
  apps/admins/src/components/Header.tsx
  apps/admins/src/components/Layout.tsx
  apps/admins/src/pages/applications/index.tsx
  apps/admins/src/pages/index.tsx
Labels: enhancement, admin app

#45 feat: auth fix
  apps/admins/src/components/Providers.tsx
  apps/admins/src/pages/_document.tsx
  apps/admins/src/server/auth.ts
Labels: bug, enhancement, admin app

#53 feat: added cards on landing page UI
  apps/lending/src/pages/index.tsx
Labels: enhancement, lending app

#59 feat: stake jusdc function fixed
  .vscode/settings.json
  apps/admins/src/cron/Contract.abi.ts
  apps/admins/src/cron/JurisEscrow.abi.ts
  apps/admins/src/cron/JurisFund.abi.ts
  apps/admins/src/env.mjs
  apps/admins/src/server/api/adminCronFixed.ts
  apps/admins/src/server/api/processDispense.ts
  apps/admins/src/server/api/routers/applications.ts
  apps/admins/tsconfig.json
  apps/jurisfund/src/server/api/routers/applications.ts
  apps/lending/package.json
  apps/lending/src/JurisFund.abi.ts
  apps/lending/src/JurisFundDiamondProxy.abi.ts
  apps/lending/src/JurisFundEscrow.abi.ts
  apps/lending/src/abi/JUSD.abi.ts
  apps/lending/src/abi/JurisFundPool.abi.ts
  apps/lending/src/components/DepositJUSDCForm.tsx
  apps/lending/src/components/Providers.tsx
  apps/lending/src/pages/_app.tsx
  apps/lending/src/pages/deposit.tsx
  packages/database/prisma/schema.prisma
  pnpm-lock.yaml
  yarn.lock
Labels: enhancement, lending app
